### PR TITLE
🐛 fix: allow subregion cloudgouv-eu-west-1c

### LINKED ISSUE #461: [Feature]: Be able to provision in cloudgouv-eu-west-1c
### Explain problem to solve

In cloud gouv, I'd like to be able to provision on 3 AZ.

### Describe the solution you would like

Support cloudgouv-eu-west-1c

### Additional context

.

### Environment

```markdown
.
```

### PR DESCRIPTION
**Pull request by jfbus**
Fixes #461

### CODE REVIEW

**Review by outscale-toa — APPROVED** [review]

File: api/v1beta1/oscmachine_validation.go [hunk 1]
```diff
@@ -183,10 +183,12 @@ func ValidateVolumeType(volumeType string) (string, error) {
 	}
 }
 
+var isValidSubregion = regexp.MustCompile(`(cloudgouv-)?(eu|us|ap)-(north|east|south|west|northeast|northwest|southeast|southwest)-[1-2][a-c]`).MatchString
```
Comment (pierreozoux) [inline api/v1beta1/oscmachine_validation.go:186]: Why not an array?

Here, it will validate `eu-west-1a` or `eu-west-2c`

cc @jfbus

Comment (jfbus) [reply api/v1beta1/oscmachine_validation.go:186]: The goal was not to force users to upgrade whenever a new region/subregion is added. This is an interim fix with a better validation than before, aiming a low-risk inclusion in v0.4.0.

The right way would be to call the API to list all available subregions, but this would require a much larger refactoring.
