### PR TITLE
fix(securityGroup): create group whit flag extraSecurityGroupRule

### LINKED ISSUE #351: [Bug]:  fail to create cluster if flag extraSecurityGroupRule enabled at creation
### What happened

the controller try to create SecurityGroupRules but the SecurityGroup is not created 

### Step to reproduce

deploy the example `cluster-machine-template-simple.yaml` after setting the `extraSecurityGroupRule` field to `true`

### Expected to happen

Cluster is well created.

### Add anything

-

### cluster-api output

-

### Environment

```markdown
- Kubernetes version: (use `kubectl version`):  1.29.5
- OS (e.g. from `/etc/os-release`):
- Kernel (e.g. `uname -a`):
- cluster-api-provider-outscale version: main branch
- cluster-api version: 1.6.3
- Install tools:
- Kubernetes Distribution:
- Kubernetes Diestribution version:
```

### PR DESCRIPTION
**Pull request by sebglon**
**What type of PR is this?**

/kind bug               Fixes securityGroup creation with flag extraSecurityGroupRule enabled

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #351

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

### CODE REVIEW

File: controllers/osccluster_securitygroup_controller.go [hunk 1]
```diff
@@ -298,7 +298,7 @@ func reconcileSecurityGroup(ctx context.Context, clusterScope *scope.ClusterScop
 
 		if !Contains(securityGroupIds, securityGroupId) && tag == nil {
 
-			if extraSecurityGroupRule {
+			if extraSecurityGroupRule && len(clusterScope.GetSecurityGroupsRef().ResourceMap) == len(clusterScope.GetSecurityGroups()) {
```
Comment (outscale-hmi) [inline controllers/osccluster_securitygroup_controller.go:301]: I think it's better to break it down into smaller, descriptive boolean len(securityGroupsRef)==len(securityGroups)
Also what if securityGroupsRef == nil || securityGroups == nil ? 
Maybe it's better to test it to avoid runtime errors

**Review by outscale-hmi — CHANGES_REQUESTED** [review]
This commit does not belong to any branch on this repository ?

File: controllers/osccluster_securitygroup_controller.go (hunk 1 above)
Comment (sebglon) [reply controllers/osccluster_securitygroup_controller.go:301]: Because of the above code, securityGroupsRef and securityGroups will never be null.

Comment (sebglon) [reply controllers/osccluster_securitygroup_controller.go]: fixed

Comment (sebglon) [reply controllers/osccluster_securitygroup_controller.go]: fixed

**Review by outscale-hmi — APPROVED** [review]
